apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: c21-2048-ingress
  namespace: c21
  # annotations:
  #   kubernetes.io/ingress.class: "haproxy"
spec:
  ingressClassName: haproxy
  rules:
  - host: "test.c21.com"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: c21-nginx-service
            port:
              number: 80