apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: c22-2048-ingress
  namespace: c22
spec:
  ingressClassName: haproxy
  rules:
  - host: "test.c22.com"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: c22-nginx-service
            port:
              number: 80