apiVersion: apps/v1
kind: Deployment
metadata:
  name: c21-nginx-2048
  namespace: c21
  labels:
    region: c21
    app: "2048"
    name: c21-nginx-2048
spec:
  replicas: 3
  selector:
    matchLabels:
      region: c21
      app: "2048"
      name: c21-nginx-2048
  template:
    metadata:
      labels:
        region: c21
        app: "2048"
        name: c21-nginx-2048
    spec:
      containers:
      - name: nginx
        image: nginx-2048
        imagePullPolicy: Never
        ports:
        - containerPort: 80
