apiVersion: v1
kind: Service
metadata:
  name: c21-nginx-service
  namespace: c21
  labels:
    service: c21-nginx-service
    region: c21
    app: "2048"
spec:
  type: NodePort
  selector:
    app: "2048"
  ports:
  - name: 2048-http
    port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 32000
  