apiVersion: v1
kind: Service
metadata:
  name: c22-nginx-service
  namespace: c22
  labels:
    service: c22-nginx-service
    region: c22
    app: "2048"
spec:
  type: NodePort
  selector:
    app: "2048"
  ports:
  - name: 2048-http
    port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 32001
  